# Generated by Django 4.2.7 on 2023-11-18 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='g1Document',
            field=models.FileField(blank=True, null=True, upload_to='document/'),
        ),
    ]
