# Generated by Django 4.2.7 on 2023-11-22 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_register_g1document'),
    ]

    operations = [
        migrations.AddField(
            model_name='return',
            name='date',
            field=models.DateField(blank=True, default='2023-11-15', null=True),
        ),
        migrations.AddField(
            model_name='return',
            name='time_duration',
            field=models.CharField(default='', max_length=150),
        ),
    ]
