# Generated by Django 4.2.7 on 2023-11-22 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_return_date_return_time_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='return',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
