# Generated by Django 4.2.7 on 2023-11-22 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_return_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='Document',
            field=models.FileField(null=True, upload_to='document/'),
        ),
    ]
