# Generated by Django 4.2.7 on 2023-11-23 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_register_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='p_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='return',
            name='r_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
