# Generated by Django 4.2.7 on 2023-11-24 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_payment_p_date_return_r_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='return',
            name='intrestAmount',
            field=models.IntegerField(default=0),
        ),
    ]
