# Generated by Django 4.2.7 on 2023-11-24 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_return_intrestamount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='return',
            name='days',
            field=models.CharField(default='0', max_length=20),
        ),
        migrations.AlterField(
            model_name='return',
            name='principal_amount',
            field=models.CharField(default='0', max_length=200),
        ),
    ]
