# Generated by Django 4.2.7 on 2023-11-24 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_return_days_alter_return_principal_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='return',
            name='intrestAmount',
        ),
    ]
