# Generated by Django 4.2.7 on 2023-11-24 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_remove_return_intrestamount'),
    ]

    operations = [
        migrations.AddField(
            model_name='return',
            name='intrestAmount',
            field=models.IntegerField(default=0),
        ),
    ]
