# Generated by Django 4.2.7 on 2023-11-29 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_return_intrestamount'),
    ]

    operations = [
        migrations.AddField(
            model_name='return',
            name='fine',
            field=models.CharField(default='0', max_length=200),
        ),
    ]
