# Generated by Django 4.2.7 on 2023-12-06 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_return_fine'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='area',
        ),
        migrations.RemoveField(
            model_name='register',
            name='join_date',
        ),
        migrations.RemoveField(
            model_name='register',
            name='limit',
        ),
        migrations.AddField(
            model_name='register',
            name='pinCode',
            field=models.CharField(default='00000', max_length=10),
        ),
    ]
