# Generated by Django 4.2.7 on 2023-12-06 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_remove_register_area_remove_register_join_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Is the account active?'),
        ),
    ]
