# Generated by Django 3.2.10 on 2023-12-16 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_auto_20231216_1203'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ActuallyIntrest',
        ),
    ]
