# Generated by Django 3.2.10 on 2023-12-16 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_delete_actuallyintrest'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActuallyIntrest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('totalUnpaid', models.IntegerField(default=0)),
                ('totalReturn', models.IntegerField(default=0)),
                ('adv', models.IntegerField(default=0)),
                ('mInterest', models.IntegerField(default=0)),
                ('PrevDues', models.IntegerField(default=0)),
                ('Pint', models.IntegerField(default=0)),
                ('total', models.IntegerField(default=0)),
                ('account', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.register')),
            ],
        ),
    ]
