# Generated by Django 3.2.10 on 2023-12-16 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_actuallyintrest'),
    ]

    operations = [
        migrations.AddField(
            model_name='actuallyintrest',
            name='account_no',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='payment',
            name='account',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='myapp.register'),
        ),
        migrations.AddField(
            model_name='return',
            name='account',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='myapp.register'),
        ),
        migrations.AlterField(
            model_name='actuallyintrest',
            name='account',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='myapp.register'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='account_no',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='return',
            name='account_no',
            field=models.CharField(default='', max_length=100),
        ),
    ]
