# Generated by Django 3.2.10 on 2023-12-16 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_auto_20231216_1248'),
    ]

    operations = [
        migrations.AddField(
            model_name='actuallyintrest',
            name='adress',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='actuallyintrest',
            name='father_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
