# Generated by Django 3.2.10 on 2023-12-16 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_auto_20231216_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='actuallyintrest',
            name='a_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
