# Generated by Django 3.2.10 on 2023-12-18 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_actuallyintrest_a_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actuallyintrest',
            name='account',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='account',
        ),
        migrations.RemoveField(
            model_name='return',
            name='account',
        ),
    ]
