# Generated by Django 3.2.10 on 2024-02-07 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_auto_20231218_1830'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='remarks',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='return',
            name='remarks',
            field=models.CharField(default='', max_length=500),
        ),
    ]
