# Generated by Django 3.2.10 on 2024-04-25 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_auto_20240207_1114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='g1Area',
        ),
        migrations.RemoveField(
            model_name='register',
            name='g2Area',
        ),
    ]
